<!-- ======================================= MAIN ============================================== -->
<main>
    <h1>Mon compte</h1>

    <?php if($statut === 'client'){ ?>

        <p>Bienvenue cher <?= htmlspecialchars($result['firstName']).' '.htmlspecialchars($result['lastName']) ?></p>
        <p>Votre identifiant client est le : <?= $id ?></p>
        
    <?php }else{ 
            if($_SESSION['admin'] === 1){ ?>
                <p><a href="bonus">Bonus</a></p>
                <p>Bienvenue Admin et Seigneur Suprême <?= htmlspecialchars($result['firstName']).' '.htmlspecialchars($result['lastName']) ?>
      <?php }else{ ?>
                <p>Bonjour <?= htmlspecialchars($result['firstName']).' '.htmlspecialchars($result['lastName']) ?>.</p>
      <?php } ?>
      <p>Matricule : <span><?= htmlspecialchars($result['matricule']) ?></span></p>
      <p>Grade : <span><?= htmlspecialchars($result['grade']) ?></span></p>
    <?php  } ?>

    <form action="account-<?= $statut ?>-<?= $id ?>" method="POST" id="<?= $statut ?>s">

        <fieldset class="edit">
            <legend id="toggle-edit" class="optionnal">Editez votre profil</legend>

            <?php if($statut === 'client'){ ?>

                <div class="field">
                    <label for="society">Société :</label>
                    <input type="text" name="society" id="society" value="<?php if($result['society'] !== 'NULL') echo htmlspecialchars($result['society']); ?>" />
                </div>

                <div class="field">
                    <label for="site-name">Nom du site :</label>
                    <input type="text" name="site-name" id="site-name" value="<?php if($result['siteName'] != null) echo htmlspecialchars($result['siteName']); ?>" />
                </div>

                <div class="field">
                    <label for="type">Type de site</label>
                    <select name="type" id="type">

                        <option <?php if($result['siteType'] === null) echo 'selected'; ?> ></option>
                        
                        <optgroup label="Magasins">
                            <option value="alimentaire" <?php if($result['siteType'] === 'alimentaire') echo 'selected'; ?> >Grande surface alimentaire</option>
                            <option value="bricolage" <?php if($result['siteType'] === 'bricolage') echo 'selected'; ?>>
                                Grande surface bricolage / ameublement
                            </option>
                            <option value="culturel" <?php if($result['siteType'] === 'culturel') echo 'selected'; ?>>
                                Grande surface culturel / divertissement
                            </option>
                            <option value="bijouterie" <?php if($result['siteType'] === 'bijouterie') echo 'selected'; ?>>Bijouterie</option>
                        </optgroup>
                        
                        <optgroup label="Transports">
                            <option value="gare" <?php if($result['siteType'] === 'gare') echo 'selected'; ?>>Gare</option>
                            <option value="aeroport" <?php if($result['siteType'] === 'aeroport') echo 'selected'; ?>>Aeroport</option>
                        </optgroup>

                        <optgroup label="Evènementiel">
                            <option value="concert" <?php if($result['siteType'] === 'concert') echo 'selected'; ?>>Concert</option>
                            <option value="sport" <?php if($result['siteType'] === 'sport') echo 'selected'; ?>>Sport</option>
                        </optgroup>

                        <option value="autre" <?php if($result['siteType'] === 'autre' || $result['siteType'] == null) echo 'selected'; ?>>Autre</option>
                    
                    </select>
                </div>

                <div class="field">
                    <label for="superficie">Superficie du site en m² :</label>
                    <input type="number" name="superficie" id="superficie" value="<?php if($result['superficie'] != null) echo htmlspecialchars($result['superficie']); ?>"/>
                </div>

            <?php } ?>

            <div class="field">
                <label for="address">Adresse :</label>
                <input type="text" name="address" id="address" value="<?php if($result['address'] != null) echo htmlspecialchars($result['address']); ?>"/>
            </div>

            <div class="field">
                <label for="postal">Code postal :</label>
                <input type="text" name="postal" id="postal" value="<?php if($result['postalCode'] != null) echo htmlspecialchars($result['postalCode']); ?>"/>
            </div>

            <div class="field">
                <label for="city">Ville :</label>
                <input type="text" name="city" id="city" value="<?php if($result['city'] != null) echo htmlspecialchars($result['city']); ?>" />
            </div>

            <div class="field">
                <label for="country">Pays :</label>
                <input type="text" name="country" id="country" value="<?php if($result['country'] != null) echo htmlspecialchars($result['country']); ?>" />
            </div>

            <div class="field">
                <label for="last-name-<?= $statut ?>">Nom :</label>
                <input 
                    type="text" 
                    name="last-name-<?= $statut ?>" 
                    id="last-name-<?= $statut ?>" 
                    value="<?= htmlspecialchars($result['lastName']) ?>" 
                    required
                />
            </div>

            <div class="field">
                <label for="first-name-<?= $statut ?>">Prénom :</label>
                <input
                    type="text"
                    name="first-name-<?= $statut ?>"
                    id="first-name-<?= $statut ?>"
                    value="<?= htmlspecialchars($result['firstName']) ?>"
                    required
                />
            </div>

            <div class="field">
                <label for="mail-<?= $statut ?>">E-mail :</label>
                <input type="email" name="mail-<?= $statut ?>" id="mail-<?= $statut ?>" value=<?= htmlspecialchars($result['mail']) ?> required/>
            </div>

            <div class="field">
                <label for="phone-<?= $statut ?>">Téléphone :</label>
                <input type="tel" name="phone-<?= $statut ?>" id="phone-<?= $statut ?>" value="<?= htmlspecialchars($result['phone']) ?>" required/>
            </div>

            <div class="field">
                <label for="pass-<?= $statut ?>">Nouveau mot de passe :</label>
                <input type="password" name="pass-<?= $statut ?>" id="pass-<?= $statut ?>" />
            </div>

            <div class="field">
                <label for="pass-verif-<?= $statut ?>">Retapez le mot de passe :</label>
                <input
                    type="password"
                    name="pass-verif-<?= $statut ?>"
                    id="pass-verif-<?= $statut ?>"
                />
            </div>

            <input
                type="submit"
                name="submit-edit-<?= $statut ?>"            
                id="submit-edit-<?= $statut ?>"
                value="Valider"
            />
        </fieldset>
    </form>

    <?php if($statut === "client"){ 
            if($orders){ ?>
        <div class="area">
            <table >
                <caption id="toggle-order">Historique de mes commandes</caption>
                <thead>                    
                    <tr>
                        <th>N°</th>
                        <th>Total Heures</th> 
                        <th>Prix TTC</th>
                        <th>Date de début</th>
                        <th>Date de fin</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($orders as $index => $value): ?>
                        <tr>
                            <td><?= htmlspecialchars($orders[$index]['id']) ?></td>
                            <td><?= intval($orders[$index]['totalHours']) ?></td>                            
                            <td><?= htmlspecialchars(number_format($orders[$index]['priceTTC'], 2, ',', ' ')).' €' ?></td>
                            <td><?= htmlspecialchars($orders[$index]['beginDate']) ?></td>
                            <td><?= htmlspecialchars($orders[$index]['endDate']) ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    <?php }else{ echo '<p>Vous n\'avez pas encore de commande</p>'; }
        } ?>

    <?php if($statut === "agent" ){ 
            if($sanctions){ ?>
        <div class="area">
            <table >
                <caption id="toggle-sanctions">Casier disciplinaire</caption>
                <thead>
                    <tr>
                    <th>Intitulé</th>
                    <th>Motif</th>
                    <th>Date de convocation</th>
                    <th>Date de notification</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($sanctions as $index => $value): ?>
                        <tr>
                            <td><?= htmlspecialchars($sanctions[$index]['entitled']) ?></td>
                            <td><?= htmlspecialchars($sanctions[$index]['reason']) ?></td>
                            <td><?= htmlspecialchars($sanctions[$index]['dateSummon']) ?></td>
                            <td><?= htmlspecialchars($sanctions[$index]['dateNotification']) ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    <?php   }else{ echo '<p>Vous n\'avez pas encore de sanctions, tant mieux !</p>'; } 
          } ?>

    <form action="" method="POST">
        <input type="submit" name="delete-<?= $statut ?>" value="Cloturer mon compte">
    </form>
</main>
