
<!-- ======================================= MAIN ============================================== -->
<main class="api">
    <article>
        <h1>Bonus Track</h1>
        <p>Avoues tu pensais que tu aurais une prime ou un truc du genre ?</p>
        <p>Bin non, je te laisse une API qui te trouvera une citation et une image de fond différente à chaque clique ou chargement, ça te fera ta culture !</p>
        <p>Désactive ce message une bonne fois pour toute pour pouvoir en profiter en cliquant <span id="close-btn">ici</span> </p>
    </article>
    <div id="pic"></div>
    <p id="quote">Citations</p>    
</main>
