
<!-- ======================================= MAIN ============================================== -->
<main class="api">
    <article>
        <h1>Bonus Track</h1>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consequatur qui repellendus architecto quis voluptatem ipsum.</p>
        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore tenetur in atque modi officia? Voluptas ipsum, dolorem 
            error ullam quia enim porro placeat explicabo, deleniti eaque odit, facilis ipsam labore vitae architecto necessitatibus 
            iusto repudiandae similique magnam adipisci culpa at
        </p>
        <p>Désactivez ce message en cliquant <span id="close-btn">ici</span> </p>
    </article>
    <div id="pic"></div>
    <p id="quote">Citations</p>    
</main>
