<!-- ======================================= MAIN ============================================== -->
<main>
    <h1>Connexion</h1>
    <div>
        <p class="<?php if(isset($notifSuccess)) echo 'success'; ?>"><?php if(isset($notifSuccess)) echo $notifSuccess; ?></p>
    </div>

    <p class="<?php if(isset($notifFail)) echo 'fail'; ?>"><?php if(isset($notifFail)) echo $notifFail; ?></p>

    <div class="data-flex">

        <form method="POST">

            <fieldset>
                <legend>Clients</legend>

                <div class="field">
                    <label for="mail-client">E-mail :</label>
                    <input type="email" name="mail-client" id="mail-client" required/>
                </div>                
                <p class="errors"><?php if(isset($_GET['client-mail'])) echo $dataStatut[$notifMc]; ?></p>

                <div class="field">
                    <label for="pass-client">Mot de passe :</label>
                    <input type="password" name="pass-client" id="pass-client" required/>
                </div>                
                <p class="errors"><?php if(isset($_GET['client-p1']) && !empty($_GET['client-p1'])) echo $dataStatut[$notifPc]; ?></p>

                <input
                    type="submit"
                    name="submit-client"
                    id="submit-client"
                    value="Connexion"
                />
            </fieldset>
        </form>

        <form method="POST">

            <fieldset>
                <legend>Agents</legend>

                <div class="field">
                    <label for="mail-agent">E-mail :</label>
                    <input type="email" name="mail-agent" id="mail-agent" required/>
                </div>                
                <p class="errors"><?php if(isset($_GET['agent-mail'])) echo $dataStatut[$notifMa]; ?></p>

                <div class="field">
                    <label for="pass-agent">Mot de passe :</label>
                    <input type="password" name="pass-agent" id="pass-agent" required/>
                </div>                
                <p class="errors"><?php if(isset($_GET['agent-p1']) && !empty($_GET['agent-p1'])) echo $dataStatut[$notifPa];  ?></p>

                <input
                    type="submit"
                    name="submit-agent"
                    id="submit-agent"
                    value="Connexion"
                />
            </fieldset>
        </form>
    </div>
</main>