<!-- ======================================= FOOTER ============================================== -->
<footer>
    <div>

        <ul>
            <li>À propos</li>
            <li id="commitment">Nos Engagements</li>
            <li id="team">Notre équipe</li>
            <li id="book">Livre d'or</li>
            <li id="conviction">Condamnations</li>
        </ul>

        <ul>
            <li id="info">Informations</li>
            <li id="condition">Conditions d'utilisation</li>
            <li id="politic">Politique de confidentialité</li>
        </ul>

        <ul>
            <li>Contact</li>
            <li>
                <a href="mailto:FakeSecurity@contact.fr" title="Envoyez nous un mail directement">
                    <i class="fas fa-envelope"></i>
                    FakeSecurity@contact.fr
                </a>
            </li>
            <li>
                <a href="tel:+00000000" title="Téléphonez nous directement">
                    <i class="fas fa-mobile-alt"></i>
                    +00000000
                </a>
            </li>
            <li>
                <a href="demand" title="Estimer ou demander votre devis" class="demand">
                    Demandez votre devis
                </a>
            </li>
        </ul>

        <ul>
            <li>Partenariats</li>
            <li id="partner">Nos partenaires</li>
            <li id="sponsor">Nos sponsors</li>
        </ul>

    </div>

    <span>        
        <a href="homepage" title="Choisissez nous, où vous aurez des problèmes">
            <img src="./assets/img/logo.png" alt="Logo FakeSecurity"/>
        </a>
    </span>

    <p>
        <a href="https://www.facebook.com" target="_blank" title="Suivez nous sur Telegram !">
            <i class="fab fa-facebook-f"></i>
        </a>
        <a href="https://www.twitter.com/?lang=fr" target="_blank" title="Followez nous sur Twitter !">
            <i class="fab fa-twitter"></i>
        </a>
        <a href="https://www.linkedin.com/" target="_blank" title="Rejoignez nous sur linkedIn !">
            <i class="fab fa-linkedin-in"></i>
        </a>
        <a href="https://www.instagram.com/?hl=fr" target="_blank" title="Rejoignez nous sur Instagram !">
            <i class="fab fa-instagram"></i>
        </a>
        <a href="https://www.telegram.org/" target="_blank" title="Rejoignez nous sur Telegram !">
            <i class="fab fa-telegram-plane"></i>
        </a>
    </p>

    <p>© FakeSecurity 2021 - Tous droits réservés</p>
</footer>