<!-- ======================================= FOOTER ============================================== -->
<footer>
    <!-- Flex Container -->
    <div>
        <!-- 
        *****************************************************************************************************
            All <li id="something"> are "button" that open the associated modal 
            For exemple : <li id="team">  will open modal <div id="teams">  
            An "s" is added to the id name on div modal
            Check assets/js/class/Toggle.js if you need (line 2 to 15)
        *****************************************************************************************************
        -->

        <!-- About -->
        <ul>
            <li>À propos</li>
            <li id="commitment">Nos Engagements</li>
            <li id="team">Notre équipe</li>
            <li id="book">Livre d'or</li>
            <li id="conviction">Condamnations</li>
        </ul>

        <!-- Informations -->
        <ul>
            <li id="info">Informations</li>
            <li id="condition">Conditions d'utilisation</li>
            <li id="politic">Politique de confidentialité</li>
        </ul>

        <!-- Contact -->
        <ul>
            <li>Contact</li>
            <li>
                <a href="mailto:FakeSecurity@contact.fr" title="Envoyez nous un mail directement">
                    <i class="fas fa-envelope"></i>
                    FakeSecurity@contact.fr
                </a>
            </li>
            <li>
                <a href="tel:+00000000" title="Téléphonez nous directement">
                    <i class="fas fa-mobile-alt"></i>
                    +00000000
                </a>
            </li>
            <li>
                <a href="demand" title="Estimer ou demander votre devis" class="demand">
                    Demandez votre devis
                </a>
            </li>
        </ul>

        <!-- Partners -->
        <ul>
            <li>Partenariats</li>
            <li id="partner">Nos partenaires</li>
            <li id="sponsor">Nos sponsors</li>
        </ul>

    </div>

    <!--  Logo  -->
    <span>        
        <a href="homepage" title="Choisissez nous, où vous aurez des problèmes">
            <img src="./assets/img/logo.png" alt="Logo FakeSecurity"/>
        </a>
    </span>

    <!--  Font awesome  -->
    <p>
        <a href="https://www.facebook.com" target="_blank" title="Suivez nous sur Telegram !">
            <i class="fab fa-facebook-f"></i>
        </a>
        <a href="https://www.twitter.com/?lang=fr" target="_blank" title="Followez nous sur Twitter !">
            <i class="fab fa-twitter"></i>
        </a>
        <a href="https://www.linkedin.com/" target="_blank" title="Rejoignez nous sur linkedIn !">
            <i class="fab fa-linkedin-in"></i>
        </a>
        <a href="https://www.instagram.com/?hl=fr" target="_blank" title="Rejoignez nous sur Instagram !">
            <i class="fab fa-instagram"></i>
        </a>
        <a href="https://www.telegram.org/" target="_blank" title="Rejoignez nous sur Telegram !">
            <i class="fab fa-telegram-plane"></i>
        </a>
    </p>

    <!-- Copyright -->
    <p>© FakeSecurity 2021 - Tous droits réservés</p>
</footer>