<!-- ======================================= HEADER ============================================== -->
<header>
    <div>
        <a href="homepage" title="Choisissez nous, où vous aurez des problèmes">
            <img src="./assets/img/logo.png" alt="Logo FakeSecurity" />
            <strong>
                Fake<span>Security</span>
            </strong>
        </a>
    </div>
    <nav>
        <ul>
            <?php if(!Access::connected()){ ?>
                <li><a href="demand">Devis</a></li>
                <li><a href="homepage">Accueil</a></li>
                <li><a href="services">Prestations</a></li>
                <li><a href="subscribe">Inscription</a></li>
                <li><a href="connexion">Connexion</a></li>
            <?php }else{ ?>
                <?php if(isset($_SESSION['admin']) && $_SESSION['admin'] === 1){ ?>
                    <li><a href="backoffice">Admin</a></li>
                    <li><a href="order">Commande</a></li>
                    <li><a href="sanction">Sanction</a></li>
                <?php }else if(isset($_SESSION['statut']) && $_SESSION['statut'] === 'agent'){ ?>
                    <li><a href="demand">Devis</a></li>
                    <li><a href="rules">Règlement</a></li>
                    <li><a href="bonus">Bonus</a></li>
                <?php }else{ ?>
                    <li><a href="demand">Devis</a></li>
                    <li><a href="quality">Qualité</a></li>
                    <li><a href="services">Prestations</a></li>
               <?php } ?>
                <li><a href='<?= "account-$statut-$id" ?>'>Profil</a></li>
                <li><a href="deconnexion">Deconnexion</a></li>
            <?php } ?>
        </ul>
    </nav>
</header>