<!-- ======================================= MAIN ============================================== -->
<main>
    <h1>Presentation</h1>

    <!-- First article -->
    <article>
        <h2>Bienvenue chez FakeSecurity</h2>

        <p>
            FakeSecurity est une société fictive ayant pour but d'escroquer ses
            clients.
        </p>

        <p>
            Notre seul et unique objectif est de trouver des pigeons, particuliers
            ou entreprises, dans le but de les plumer sans leur fournir la
            prestation attendue.
        </p>

        <p>
            Nous disposons d'un savoir faire unique dans l'escroquerie à grande et
            petite échelle. Ainsi, en souscrivant à l'une de nos offres, vous êtes
            absolument certain de vous faire entuber de façon exceptionnelle.
        </p>
    </article>

    <!-- Second article -->
    <article>
        <h2>Objectifs et Philosophie</h2>

        <p>
            Notre seul et unique objectif est l'argent, sous toutes ses formes :
        </p>

        <ul>
            <li>Cash</li>
            <li>Virements</li>
            <li>Chèques</li>
            <li>Crypto-monnaies</li>
            <li>Or</li>
            <li>Oeuvres d'art (seulement de valeur)</li>
            <li>Matières premières rare</li>
            <li>Paypal, Skril, Neteller etc...</li>
        </ul>

        <p>
            Notre philosophie d'entreprise se résume à la pensée de l'illustre
            Skippy, gourou de la secte Richenous. Sa plus célèbre citation est la
            suivante :
            <q>Tout bien que tu détiens est un soucis qui te retiens</q>
        </p>

        <p>
            Et Skippy, dans sa grande bienveillance, se vouait chaque jour à
            délester ses fidèles de tous leurs soucis.
        </p>
        
    </article>

    <!-- Go Devis button - SVG & BEM__ -->
    <div class="button">
        <a href="demand" title="Faites estimer votre devis et envoyer la demande">
            <svg height="60px" width="320px">
                <rect class="button__rect" height="60px" width="320px"></rect>
            </svg>

            <div class="button__text">Go Devis</div>
        </a>
    </div>

    <!-- Last article (third) -->
    <article>
        <h2>Rencontrez nous</h2>

        <p>Vous souhaitez nous rencontrer ? Rien de plus simple !</p>

        <p>
            Nous serons présent au salon de la sécurité Escro-Protection-Sécurité
            du 28 au 30 septembre 2021 ayant lieu à Paris.
        </p>

        <p>
            Pour nous rejoindre à ce salon vous devrez vous rendre au 34 rue de la
            corniche 75017, marcher pendant 34 minutes et 17 secondes à 8km/h à un
            angle de 30° par rapport au batiment se trouvant face a vous. Ensuite
            il vous faudra tourner a gauche, marcher a nouveau 30 minutes, tourner
            a droite a la prochaine intersection ensuite tourner sur un angle de
            77,3° précisément en direction du soleil, après 12 minutes de marche,
            plongez dans la Seine, nagez une bonne 20aine de minutes, plongez en
            apnée pendant 15 minutes ensuite regagnez la terre ferme puis sonnez à
            la porte face a vous. Dès lors le portier vous demandera le mot de
            passe, qui est le suivant :
            "youpla lilalou laplou leboumy ihoha roflmao pwetpwet", vous devrez lui
            donner le mot de passe du 1er coup, sans vous tromper et sans le lire
            que ce soit sur un support papier ou numérique, sous peine de
            délencher la colère du portier qui vous agressera alors sauvagement a
            coup de barre de fer.
        </p>

        <p>
            Et voilà, vous êtes arrivé ! Simple non ? Il ne vous restera plus qu'à
            monter les 25 étages vous séparant de la salle de réunion que nous
            occuperons.
        </p>

        <p>
            Note aux clients : FakeSecurity se fera un plaisir de vous recevoir,
            par contre si vous souhaitez vous désaltérer ou vous restaurer,
            ammenez vos propres affaires, on est pas là pour faire des sandwich.
        </p>

        <p>
            Note aux demandeurs d'emploi : dans un contexte sanitaire et
            économique compliqué, la société FakeSecurity à pleinement conscience
            de vos difficultés à (re)trouver un emploi, soucieux de respecter nos
            valeurs, nous avons donc décidé de profiter de la situation. Ainsi, si
            vous souhaitez postuler chez nous, il est fortement recommandé (par là
            nous entendons obligatoire, sauf pistonnage) de prévoir une offrande
            de valeur.
        </p>
    </article>
</main>