<!-- ======================================= MAIN ============================================== -->
<main>
    <h1>Presentation</h1>

    <article>
        <h2>Bienvenue chez FakeSecurity</h2>

        <p>
            Lorem ipsum dolor sit, amet consectetur adipisicing.
        </p>

        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita veniam illum, ipsam odio totam architecto 
            alias culpa et ullam! Mollitia suscipit laboriosam quae vitae beatae!
        </p>

        <p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam laudantium numquam quasi libero! 
            Beatae eligendi dolor eum maiores labore totam, hic neque similique, iusto ex quo reprehenderit, quis aliquam! Mollitia?
        </p>
    </article>

    <article>
        <h2>Objectifs et Philosophie</h2>

        <p>
            Lorem ipsum dolor, sit amet consectetur adipisicing elit. Cum, ipsam!
        </p>

        <ul>
            <li>Lorem</li>
            <li>Ipsum</li>
            <li>Dolor</li>
            <li>Consectetur</li>
            <li>Elit</li>
            <li>Lorem ipsum dolor sit</li>
            <li>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Suscipit.</li>
            <li>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptatibus, officia tempore facere iste sunt culpa?</li>
        </ul>

        <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta, nemo temporibus quisquam maiores earum odio ipsum 
            repellat consequatur qui eos!
            <q>Lorem ipsum dolor sit amet consectetur.</q>
        </p>

        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium inventore eius id facilis.
        </p>
        
    </article>

    <div class="button">
        <a href="demand" title="Faites estimer votre devis et envoyer la demande">
            <svg height="60px" width="320px">
                <rect class="button__rect" height="60px" width="320px"></rect>
            </svg>

            <div class="button__text">Go Devis</div>
        </a>
    </div>

    <article>
        <h2>Rencontrez nous</h2>

        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>

        <p>
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Impedit eius tempore voluptatem nulla, 
            eveniet repellat hic nihil praesentium.
        </p>

        <p>
            Lorem ipsum dolor, sit amet consectetur adipisicing elit. In possimus dolor, voluptatum magnam qui iste voluptate. 
            Distinctio labore, praesentium, ullam recusandae harum nulla excepturi omnis inventore explicabo tempora, dolores temporibus.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero quia ad voluptatem iste a! Iure labore eligendi a pariatur 
            provident officiis voluptas, voluptatibus eos veniam natus rerum, odio sequi consequatur.
            Consectetur inventore ratione tempora voluptatibus velit amet, illum fugiat, fuga voluptatum tenetur nisi quos similique? Nisi 
            debitis enim cumque deserunt, deleniti officia ipsa voluptatibus, recusandae dolorem voluptates et porro perspiciatis.
            Consequuntur explicabo, veritatis dolores numquam reiciendis unde expedita corporis illo nesciunt laborum esse magnam. Rerum 
            voluptatum quisquam nemo sed voluptatibus adipisci ipsam. Qui eveniet assumenda sapiente quam ipsum nulla debitis.
        </p>

        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium voluptatem aspernatur, ipsam asperiores est error magnam 
            neque dolor eius. Ad magni accusamus, officiis id repudiandae quia, quod, tenetur neque quas fugiat tempore architecto obcaecati 
            officia iusto. Error quisquam sapiente nostrum?
        </p>

        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium voluptatem aspernatur, ipsam asperiores est error magnam 
            neque dolor eius. Ad magni accusamus, officiis id repudiandae quia, quod, tenetur neque quas fugiat tempore architecto obcaecati 
            officia iusto. Error quisquam sapiente nostrum?
        </p>

        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto ducimus corrupti possimus recusandae voluptas, est, quae 
            reprehenderit dolore perspiciatis corporis odio vero dicta? Animi odit eos facilis quia atque sequi.
            Quidem assumenda et optio vel dolores qui, odio tempora consequatur perspiciatis est numquam beatae esse temporibus laudantium. 
            Hic natus ab assumenda. Sit voluptates fuga cum aliquid eveniet similique ipsa at.
        </p>
    </article>
</main>