
<!-- ======================================= MODALS ============================================== -->
<div id="commitments" class="modal">
    <div>
        <i class="fas fa-times"></i>
        <h3>Nos engagements</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing.</p>
    </div>
</div>

<div id="teams" class="modal">
    <div>
        <i class="fas fa-times"></i>
        <h3>Notre équipe</h3>
        <h4>Direction</h4>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing.</p>

        <h4>Responsables de Secteurs</h4>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing.</p>

        <h4>Agents de terrain</h4>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing.</p>

    </div>
</div>

<div id="books" class="modal">
    <div>
        <i class="fas fa-times"></i>
        <h3>Livre d'or</h3>
        <p>Vous trouverez ci-dessous quelques témoignages nous concernant.</p>
        <h4>Clients</h4>
        <p>
            lorem :
            <q>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde ut suscipit quo esse impedit, illum reiciendis 
                commodi repellat dolorem quibusdam tempore odit, id eius expedita nesciunt blanditiis eveniet nisi ullam qui? Quidem, 
                amet facilis ratione atque cumque quisquam eligendi debitis?
            </q>
        </p>
        <p>
            lorem :
            <q>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde ut suscipit quo esse impedit, illum reiciendis 
                commodi repellat dolorem quibusdam tempore odit, id eius expedita nesciunt blanditiis eveniet nisi ullam qui? Quidem, 
                amet facilis ratione atque cumque quisquam eligendi debitis?
            </q>
        </p>
        <p>
            lorem :
            <q>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus, corrupti!
            </q>
        </p>
        <p>
            lorem :
            <q>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde ut suscipit quo esse impedit, illum reiciendis 
                commodi repellat dolorem quibusdam tempore odit, id eius expedita nesciunt blanditiis eveniet nisi ullam qui? Quidem, 
                amet facilis ratione atque cumque quisquam eligendi debitis?
            </q>
        </p>

        <h4>Partenaires</h4>
        <p>
            lorem :
            <q>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde ut suscipit quo esse impedit, illum reiciendis 
                commodi repellat dolorem quibusdam tempore odit, id eius expedita nesciunt blanditiis eveniet nisi ullam qui? Quidem, 
                amet facilis ratione atque cumque quisquam eligendi debitis?
            </q>
        </p>

        <h4>Salariés</h4>
        <p>
            lorem :
            <q>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde ut suscipit quo esse impedit, illum reiciendis 
                commodi repellat dolorem quibusdam tempore odit, id eius expedita nesciunt blanditiis eveniet nisi ullam qui? Quidem, 
                amet facilis ratione atque cumque quisquam eligendi debitis?
            </q>
        </p>
        <p>
            lorem :
            <q>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde ut suscipit quo esse impedit, illum reiciendis 
                commodi repellat dolorem quibusdam tempore odit, id eius expedita nesciunt blanditiis eveniet nisi ullam qui? Quidem, 
                amet facilis ratione atque cumque quisquam eligendi debitis?
            </q>
        </p>
    </div>
</div>

<div id="convictions" class="modal">
    <div>
        <i class="fas fa-times"></i>
        <h3>Nos condamnations</h3>
        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque eligendi omnis aperiam unde, 
            tempora iste expedita illum quod possimus dicta.
        </p>
        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque eligendi omnis aperiam unde, 
            tempora iste expedita illum quod possimus dicta.
        </p>
        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque eligendi omnis aperiam unde, 
            tempora iste expedita illum quod possimus dicta.
        </p>
        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque eligendi omnis aperiam unde, 
            tempora iste expedita illum quod possimus dicta.
        </p>
        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque eligendi omnis aperiam unde, 
            tempora iste expedita illum quod possimus dicta.
        </p>
        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque eligendi omnis aperiam unde, 
            tempora iste expedita illum quod possimus dicta.
        </p>
        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque eligendi omnis aperiam unde, 
            tempora iste expedita illum quod possimus dicta.
        </p>
        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque eligendi omnis aperiam unde, 
            tempora iste expedita illum quod possimus dicta.
        </p>
        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque eligendi omnis aperiam unde, 
            tempora iste expedita illum quod possimus dicta.
        </p>
        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque eligendi omnis aperiam unde, 
            tempora iste expedita illum quod possimus dicta.
        </p>
        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque eligendi omnis aperiam unde, 
            tempora iste expedita illum quod possimus dicta.
        </p>
        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque eligendi omnis aperiam unde, 
            tempora iste expedita illum quod possimus dicta.
        </p>
        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque eligendi omnis aperiam unde, 
            tempora iste expedita illum quod possimus dicta.
        </p>
        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque eligendi omnis aperiam unde, 
            tempora iste expedita illum quod possimus dicta.
        </p>
        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque eligendi omnis aperiam unde, 
            tempora iste expedita illum quod possimus dicta.
        </p>
    </div>
</div>

<div id="conditions" class="modal">
    <div>
        <i class="fas fa-times"></i>
        <h3>Conditions d'utilisation</h3>
        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque eligendi omnis aperiam unde, 
            tempora iste expedita illum quod possimus dicta.
        </p>
        <p>Lorem ipsum dolor sit amet consectetur.</p>

        <h4> Article 1 : Objet </h4>
        <p>
            Les présentes CGU ou Conditions Générales d’Utilisation encadrent
            juridiquement l’utilisation des services du site FakeSecurity
            (ci-après dénommé « le site »). Constituant le contrat entre la
            société FakeSecurity, l’Utilisateur, l’accès au site doit être précédé
            de l’acceptation de ces CGU. L’accès à cette plateforme signifie
            l’acceptation des présentes CGU.
        </p>

        <h4> Article 2 : Mentions légales </h4>
        <p>
            L’édition du site FakeSecurity est assurée par la société FakeSecurity
            inscrite au RCS sous le numéro 000 000 000, dont le siège social est
            localisé au 3 Rue Mêles toi de tes Affaires, 00000, Nulle Part, Mars
            Métropolitain. L’hébergeur du site FakeSecurity.fr est la société
            Opaque, sise au 5 Rue tu Cherches vraiment les Problèmes, 000000 Chez
            toi, France.
        </p>

        <h4> Article 3 : Accès au site </h4>
        <p>
            Le site FakeSecurity permet d’accéder aux services suivants :
            consultations et achats de nos prestations. Le site est accessible
            gratuitement depuis n’importe où par tout utilisateur disposant d’un
            accès à Internet. Tous les frais nécessaires pour l’accès aux services
            (matériel informatique, connexion Internet…) sont à la charge de
            l’utilisateur. L’accès aux services dédiés aux membres s’effectue à
            l’aide d’un identifiant et d’un mot de passe. Pour des raisons de
            maintenance ou autres, l’accès au site peut être interrompu ou
            suspendu par l’éditeur sans préavis ni justification.
        </p>

        <h4>Article 4 : Collecte des données</h4>
        <p>
            Pour la création du compte de l’Utilisateur, la collecte des
            informations au moment de l’inscription sur le site est nécessaire et
            obligatoire. L'utilisateur est informé que toutes ses données sont
            susceptibles d'être utilisées a des fins malveillantes, frauduleuses
            et pour tout but lucratif. Conformément à aucune loi et à notre bon
            vouloir, l’Utilisateur dispose du droit d’accéder, de rectifier, de
            supprimer et d’opposer ses données personnelles seulement avec notre
            consentement préalable écrit.
        </p>

        <h4>Article 5 : Propriété intellectuelle</h4>
        <p>
            Les marques, logos ainsi que les contenus du site FakeSecurity
            (illustrations graphiques, textes…) sont protégés par le Code de la
            propriété intellectuelle, par le droit d’auteur et par une équipe de
            la mafia. La reproduction et la copie des contenus par l’Utilisateur
            requièrent une autorisation préalable du site. Dans ce cas, toute
            utilisation à des usages commerciaux ou à des fins publicitaires est
            proscrite.
        </p>

        <h4>Article 6 : Responsabilité</h4>
        <p>
            Bien que les informations publiées sur le site soient réputées
            fiables, le site se réserve la faculté d’une non-garantie de la
            fiabilité des sources. Les informations diffusées sur le site
            FakeSecurity sont présentées à titre purement informatif et sont sans
            valeur contractuelle. En dépit des mises à jour régulières, la
            responsabilité du site ne peut être engagée en cas de modification des
            dispositions administratives et juridiques apparaissant après la
            publication. Il en est de même pour l’utilisation et l’interprétation
            des informations communiquées sur la plateforme. Le site décline toute
            responsabilité concernant les éventuels virus pouvant infecter le
            matériel informatique de l’Utilisateur après l’utilisation ou l’accès
            à ce site, il est également possible que nos équipes tentent de vous
            hacker, ce que vous acceptez sans réserves. Le site ne peut être tenu
            pour responsable en cas de force majeure ou du fait imprévisible et
            insurmontable d’un tiers. La garantie totale de la sécurité et la
            confidentialité des données n’est pas assurée par le site.
        </p>

        <h4>Article 7 : Liens hypertextes</h4>
        <p>
            Le site peut être constitué de liens hypertextes. En cliquant sur ces
            derniers, l’Utilisateur sortira de la plateforme. Cette dernière n’a
            pas de contrôle et ne peut pas être tenue responsable du contenu des
            pages web relatives à ces liens. L'utilisateur accepte d'être redirigé
            sur des sites malveillants.
        </p>

        <h4>Article 8 : Cookies</h4>
        <p>
            Lors des visites sur le site, l’installation automatique d’un (ou
            plusieurs) cookie(s) sur le logiciel de navigation de l’Utilisateur
            peut survenir. Les cookies correspondent à de petits fichiers déposés
            temporairement sur le disque dur de l’ordinateur de l’Utilisateur. Ces
            cookies sont nécessaires pour assurer l’accessibilité et la navigation
            sur le site. Ces fichiers ne comportent pas d’informations
            personnelles et ne peuvent pas être utilisés pour l’identification
            d’une personne. L’information présente dans les cookies est utilisée
            pour améliorer les performances de navigation sur le site
            FakeSecurity.fr. En naviguant sur le site, l’Utilisateur accepte les
            cookies. Leur désactivation peut s’effectuer via les paramètres du
            logiciel de navigation.
        </p>

        <h4>Article 9 : Publication par l’Utilisateur</h4>
        <p>
            Le site ne permet pas aux utilisateurs de publier. L'utilisateur est
            prié de naviguer sans rien nous dire, à moins qu'il souhaite souscrire
            a l'une ou plusieurs de nos offres.
        </p>

        <h4>Article 10 : Durée du contrat</h4>
        <p>
            Le présent contrat est valable pour une durée indéterminée. Le début
            de l’utilisation des services du site marque l’application du contrat
            à l’égard de l’Utilisateur.
        </p>

        <h4> Article 11 : Droit applicable et juridiction compétente </h4>
        <p>
            Le présent contrat est soumis à la législation Mafieuse. L’absence de
            résolution à l’amiable des cas de litige entre les parties implique le
            recours aux tribunaux mafieux compétents pour régler le contentieux,
            ce qui signifie dans la majorités des cas un décès pour le(s)
            plaignant(s).
        </p>
    </div>
</div>

<div id="politics" class="modal">
    <div>
        <i class="fas fa-times"></i>
        <h3>Politique de confidentialité</h3>
        <p>Lorem ipsum :</p>
        <ul>
            <li>Lorem ipsum.</li>
            <li>Lorem ipsum.</li>
            <li>Lorem ipsum.</li>
        </ul>
    </div>
</div>

<div id="partners" class="modal">
    <div>
        <i class="fas fa-times"></i>
        <h3>Nos partenaires</h3>
        <p>Pas de partenaires</p>        
    </div>    
</div>

<div id="sponsors" class="modal">
    <div>
        <i class="fas fa-times"></i>
        <h3>Nos sponsors</h3>
        <p>Pas de sponsors.</p>
    </div>
</div>