
<!-- ======================================= MODALS ============================================== -->
<!-- 
*****************************************************************************************************
    All <div id="somethings"> are modals that are openned by the associated <li id="something"> 
    For exemple : <li id="team">  will open modal <div id="teams">  
    An "s" is removed in the <li id="">
    Check assets/js/class/Toggle.js if you need (line 2 to 15)
*****************************************************************************************************
--> 

<!-- COMMITMENTS -->
<div id="commitments" class="modal">
    <div>
        <i class="fas fa-times"></i>
        <h3>Nos engagements</h3>
        <p>
            Profits : engagés à 200% dans ce domaine, nous sommes de véritables
            pionniers.
        </p>
        <p>Ecologie : rien à battre.</p>
        <p>Commerce équitable : rien à battre.</p>
        <p>Respect des droits de l'Homme : rien à battre.</p>
        <p>Inclusivité et diversité : rien à battre.</p>
        <p>Respect des lois : rien à battre.</p>
        <p>Respect des valeurs démocratiques : rien à battre.</p>
    </div>
</div>

<!-- TEAMS -->
<div id="teams" class="modal">
    <div>
        <i class="fas fa-times"></i>
        <h3>Notre équipe</h3>
        <h4>Direction</h4>
        <p>
            Guillaume R. dit "Le Blagueur, Le Parrain, Le Cerveau" - Magnat du
            crime, les personnes qui le déçoivent disparraissent mystérieusement.
        </p>

        <h4>Responsables de Secteurs</h4>
        <p>
            Guillaume P. dit "L'énergivore" - Responsable du vol d'énérgie et du
            traffic de carte graphiques.
        </p>
        <p>
            Grégoire D. dit "Great D" - Responsable des contrats, du démarchage
            aggressif, du chantage, du blanchiment d'argent et des comptes.
        </p>

        <h4>Agents de terrain</h4>
        <p>
            Quentin D. dit "Caption Master" - en charge des kidnappings et
            assassinats, son camping car lui permet de transporter des corps
            jusqu'en forêt et autres endroits pratiques.
        </p>
        <p>
            Thomas T. dit "Yametekudasai" - en charge du divertissement, il aime
            prendre des voix féminines d'animés japonais.
        </p>
        <p>
            Jérémie G. dit "Le Connaisseur" - en charge du hacking et des
            technologies, il nous sort souvent des machins dont on à jamais
            entendu parlé.
        </p>
        <p>
            Yoann A. dit "El yoyoz" - en charge de la gestion des esclaves et de
            leurs surveillances, on ne sait pas grand chose a son sujet.
        </p>

        <h4>Esclaves</h4>
        <p>
            Tommy C. dit "Gros Tommy" - fait également partit d'un gang appelé
            KPOP Masters, il est chargé du racket et de la vente de drogues. C'est
            un alcoolique notoire.
        </p>
        <p>
            Salah K. dit "La Fouine" - fait également partit d'un gang appelé KPOP
            Masters, il est chargé des arnaques au Bitcoin et autres
            crypto-monnaies.
        </p>
        <p>
            Un anonyme dit "Soja Man" - fait du traffic de sauce soja sans qu'on
            lui ai rien demandé, il ne produit rien, n'apporte pas de bénéfices et
            se shoot a la sauce Soja toute la journée.
        </p>
    </div>
</div>

<!-- BOOKS -->
<div id="books" class="modal">
    <div>
        <i class="fas fa-times"></i>
        <h3>Livre d'or</h3>
        <p>Vous trouverez ci-dessous quelques témoignages nous concernant.</p>
        <h4>Clients</h4>
        <p>
            David P, client vérifié :
            <q>
                Entreprise qui tient ses promesses, j'avais beaucoup d'argent dont
                je souhaitais me débarasser, FakeSecurity.com m'a plumer dans des
                délais records et sans me fournir la moindre contrepartie. Je
                recommande pour les gens qui ont beaucoup trop d'argent.
            </q>
        </p>
        <p>
            Romain D, client vérifié :
            <q>
                Gérant d'une supérette, j'ai fait appel a FakeSecurity pour un
                service de sécurité dont je n'avais absolument pas besoin, je me
                suis entendu avec le PDG pour établir un système de blanchiment
                d'argent. Cher mais efficace, je recommande leurs services !
            </q>
        </p>
        <p>
            Amélie A, client non vérifié :
            <q>
                They aren't kind at all, I am unhappy !
            </q>
        </p>
        <p>
            Jean U, client non vérifié :
            <q>
                I asked them if they could secure a protest in NY, they told me
                they don't give a shit about protest but they also said
                that they were agree to take our money without doing anything ! Shame
                on you FakeSecurity.
            </q>
        </p>

        <h4>Partenaires</h4>
        <p>
            Chang Z, partenaire :
            <q>
                FakeSecurity treat their employees like garbage, i've never seen
                that in my entire life, i'm a bit impressed
            </q>
        </p>

        <h4>Salariés</h4>
        <p>
            Youssef Z, représentant syndical :
            <q>
                La société ne m'a pas versé mon salaire depuis des mois, elle ne
                respect ni le temps de travail maximal ni le temps de repos minimale
                inscrit dans la convention collective, proprement scandaleux, des
                purs VOYOUS.
            </q>
        </p>
        <p>
            Aminata N, ancienne salariée :
            <q>
                J'ai travaillé dans cette société de 2005 a 2011, j'ai été victime
                de harcèlement moral et sexuel de la part de mes supérieurs
                hiérarchiques, lorsque j'ai envoyé un courrier recommandé pour
                dénoncer les faits j'ai été licencié sans motif ! Malheureusement je
                n'ai pas les moyens de les poursuivres en justice... Restez loin de
                cette société ce sont des porcs !
            </q>
        </p>
    </div>
</div>

<!-- CONVICTIONS -->
<div id="convictions" class="modal">
    <div>
        <i class="fas fa-times"></i>
        <h3>Nos condamnations</h3>
        <p>
            Utilisation d'armes chimiques, Jugement par contumas du 4 mars 2019,
            Texas
        </p>
        <p>Meurtres avec préméditation, Jugement du 19 octobre 2018, Brest</p>
        <p>Traffic d'influence et chantage, Jugement du 15 aout 2018, Lens</p>
        <p>Traffic d'armes, Jugement par contumas du 13 mai 2017, Tokyo</p>
        <p>
            Appel a la rebellion et a l'insurrection, Jugement du 28 juin 2016,
            Paris
        </p>
        <p>
            Tentative de putsch en Namibie et Crime contre l'humanité, Jugement du
            3 juillet 2014, Tribunal international des Nations Unies.
        </p>
        <p>
            Traffic international d'êtres humains, Jugement du 17 novembre 2012,
            Washington.
        </p>
        <p>Dégradation en bande organisée, Jugement du 15 janvier 2010, Quebec</p>
        <p>Traffic de stupéfiants, Jugement du 22 septembre 2009, Vendée</p>
        <p>Discrimination raciale, Jugement du 29 février 2008, Lyon</p>
        <p>
            Discrimination basée sur le sexe et l'orientation sexuelle, Jugement
            du 7 février 2008, Marseille
        </p>
        <p>Discrimination syndicale, Jugement du 6 mars 2005, Bobigny</p>
        <p>Fraude fiscale, Jugement du 12 janvier 2005, New York</p>
        <p>Blanchiment d'argent, Jugement du 18 mai 2004, Paris</p>
        <p>Escroquerie et Abus de confiance, Jugement du 27 novembre 2002, Rouen</p>
    </div>
</div>

<!-- CONDITIONS -->
<div id="conditions" class="modal">
    <div>
        <i class="fas fa-times"></i>
        <h3>Conditions d'utilisation</h3>
        <p>
            En poursuivant la navigation sur notre site vous acceptez de facto la
            totalité de nos conditions d'utilisation.
        </p>
        <p>Nos conditions d'utilisation sont les suivantes :</p>

        <h4> Article 1 : Objet </h4>
        <p>
            Les présentes CGU ou Conditions Générales d’Utilisation encadrent
            juridiquement l’utilisation des services du site FakeSecurity
            (ci-après dénommé « le site »). Constituant le contrat entre la
            société FakeSecurity, l’Utilisateur, l’accès au site doit être précédé
            de l’acceptation de ces CGU. L’accès à cette plateforme signifie
            l’acceptation des présentes CGU.
        </p>

        <h4> Article 2 : Mentions légales </h4>
        <p>
            L’édition du site FakeSecurity est assurée par la société FakeSecurity
            inscrite au RCS sous le numéro 000 000 000, dont le siège social est
            localisé au 3 Rue Mêles toi de tes Affaires, 00000, Nulle Part, Mars
            Métropolitain. L’hébergeur du site FakeSecurity.fr est la société
            Opaque, sise au 5 Rue tu Cherches vraiment les Problèmes, 000000 Chez
            toi, France.
        </p>

        <h4> Article 3 : Accès au site </h4>
        <p>
            Le site FakeSecurity permet d’accéder aux services suivants :
            consultations et achats de nos prestations. Le site est accessible
            gratuitement depuis n’importe où par tout utilisateur disposant d’un
            accès à Internet. Tous les frais nécessaires pour l’accès aux services
            (matériel informatique, connexion Internet…) sont à la charge de
            l’utilisateur. L’accès aux services dédiés aux membres s’effectue à
            l’aide d’un identifiant et d’un mot de passe. Pour des raisons de
            maintenance ou autres, l’accès au site peut être interrompu ou
            suspendu par l’éditeur sans préavis ni justification.
        </p>

        <h4>Article 4 : Collecte des données</h4>
        <p>
            Pour la création du compte de l’Utilisateur, la collecte des
            informations au moment de l’inscription sur le site est nécessaire et
            obligatoire. L'utilisateur est informé que toutes ses données sont
            susceptibles d'être utilisées a des fins malveillantes, frauduleuses
            et pour tout but lucratif. Conformément à aucune loi et à notre bon
            vouloir, l’Utilisateur dispose du droit d’accéder, de rectifier, de
            supprimer et d’opposer ses données personnelles seulement avec notre
            consentement préalable écrit.
        </p>

        <h4>Article 5 : Propriété intellectuelle</h4>
        <p>
            Les marques, logos ainsi que les contenus du site FakeSecurity
            (illustrations graphiques, textes…) sont protégés par le Code de la
            propriété intellectuelle, par le droit d’auteur et par une équipe de
            la mafia. La reproduction et la copie des contenus par l’Utilisateur
            requièrent une autorisation préalable du site. Dans ce cas, toute
            utilisation à des usages commerciaux ou à des fins publicitaires est
            proscrite.
        </p>

        <h4>Article 6 : Responsabilité</h4>
        <p>
            Bien que les informations publiées sur le site soient réputées
            fiables, le site se réserve la faculté d’une non-garantie de la
            fiabilité des sources. Les informations diffusées sur le site
            FakeSecurity sont présentées à titre purement informatif et sont sans
            valeur contractuelle. En dépit des mises à jour régulières, la
            responsabilité du site ne peut être engagée en cas de modification des
            dispositions administratives et juridiques apparaissant après la
            publication. Il en est de même pour l’utilisation et l’interprétation
            des informations communiquées sur la plateforme. Le site décline toute
            responsabilité concernant les éventuels virus pouvant infecter le
            matériel informatique de l’Utilisateur après l’utilisation ou l’accès
            à ce site, il est également possible que nos équipes tentent de vous
            hacker, ce que vous acceptez sans réserves. Le site ne peut être tenu
            pour responsable en cas de force majeure ou du fait imprévisible et
            insurmontable d’un tiers. La garantie totale de la sécurité et la
            confidentialité des données n’est pas assurée par le site.
        </p>

        <h4>Article 7 : Liens hypertextes</h4>
        <p>
            Le site peut être constitué de liens hypertextes. En cliquant sur ces
            derniers, l’Utilisateur sortira de la plateforme. Cette dernière n’a
            pas de contrôle et ne peut pas être tenue responsable du contenu des
            pages web relatives à ces liens. L'utilisateur accepte d'être redirigé
            sur des sites malveillants.
        </p>

        <h4>Article 8 : Cookies</h4>
        <p>
            Lors des visites sur le site, l’installation automatique d’un (ou
            plusieurs) cookie(s) sur le logiciel de navigation de l’Utilisateur
            peut survenir. Les cookies correspondent à de petits fichiers déposés
            temporairement sur le disque dur de l’ordinateur de l’Utilisateur. Ces
            cookies sont nécessaires pour assurer l’accessibilité et la navigation
            sur le site. Ces fichiers ne comportent pas d’informations
            personnelles et ne peuvent pas être utilisés pour l’identification
            d’une personne. L’information présente dans les cookies est utilisée
            pour améliorer les performances de navigation sur le site
            FakeSecurity.fr. En naviguant sur le site, l’Utilisateur accepte les
            cookies. Leur désactivation peut s’effectuer via les paramètres du
            logiciel de navigation.
        </p>

        <h4>Article 9 : Publication par l’Utilisateur</h4>
        <p>
            Le site ne permet pas aux utilisateurs de publier. L'utilisateur est
            prié de naviguer sans rien nous dire, à moins qu'il souhaite souscrire
            a l'une ou plusieurs de nos offres.
        </p>

        <h4>Article 10 : Durée du contrat</h4>
        <p>
            Le présent contrat est valable pour une durée indéterminée. Le début
            de l’utilisation des services du site marque l’application du contrat
            à l’égard de l’Utilisateur.
        </p>

        <h4> Article 11 : Droit applicable et juridiction compétente </h4>
        <p>
            Le présent contrat est soumis à la législation Mafieuse. L’absence de
            résolution à l’amiable des cas de litige entre les parties implique le
            recours aux tribunaux mafieux compétents pour régler le contentieux,
            ce qui signifie dans la majorités des cas un décès pour le(s)
            plaignant(s).
        </p>
    </div>
</div>

<!-- POLITICS -->
<div id="politics" class="modal">
    <div>
        <i class="fas fa-times"></i>
        <h3>Politique de confidentialité</h3>
        <p>Notre politique de confidentialité est la suivante :</p>
        <ul>
            <li>Aucune confidentialité n'est garantie.</li>
            <li>
                Nous utiliserons vos données comme bon nous semble si cela sert nos
                interêts.
            </li>
            <li>
                En cas de réclamation, vous pourrez toujours allez vous brosser.
            </li>
        </ul>
    </div>
</div>

<!-- PARTNERS -->
<div id="partners" class="modal">
    <div>
        <i class="fas fa-times"></i>
        <h3>Nos partenaires</h3>
        <p>Liste de nos partenaires, non exhaustive.</p>
        <h4>FakeNettoyage</h4>
        <p>
            Nous faisons souvent appel à ce partenaire, il nettoie impeccable les scènes de crimes que nous laissons derrière nous, 
            et ne poses jamais de questions.
        </p>
        <a href="#" target="_blank" title="Allez sur le site de notre partenaire">
            <img src="./assets/img/nettoyage.jpg" alt="Logo de la société FakeNettoyage"/>
        </a>

        <h4>FakeCompta</h4>
        <p>
            Vous avez besoin d'optimisation fiscale, de blanchir de l'argent ou de trafiquer vos livres de compte ?
            Faites appel à notre partenaires qui excelle en la matière.
        </p>
        <a href="#" target="_blank" title="Allez sur le site de notre partenaire">
            <img src="./assets/img/comptabilite.jpg" alt="Logo de la société FakeCompta"/>
        </a>

        <h4>Bourrage d'urnes</h4>
        <p>
            Nos amis vous proposent de truquer n'importe quelle éléction (politique, syndicale etc...) pour un prix imbattable.
        </p>
        <p>
            Nous faisons régulièrement appels à eux pour nous même ou nos clients, satisfaction garantie (ou pas remboursé).
        </p>
        <a href="#" target="_blank" title="Allez sur le site de notre partenaire">
            <img src="./assets/img/bourrage.jpg" alt="Logo de la société Bourrage d'urne"/>
        </a>
    </div>    
</div>
    
<!-- SPONSORS -->
<div id="sponsors" class="modal">
    <div>
        <i class="fas fa-times"></i>
        <h3>Nos sponsors</h3>
        <p>Liste de nos sponsors, non exhaustive.</p>
        <h4>Le fisc Français & les Ministres qui ont des phobies administratives</h4>
        <p>
            Nos amis qui travaillent au sein du ministère de l'économie savent très bien que les phobies administratives
            sont tout à fait dévastatrices pour ceux qui sont touché par ce grand mal.
            Et puis il y a également les fameux oublis (oups j'ai oublié de déclarer 200 000€ alors que j'ai un comptable, pas de bol).
        </p>
        <p>De ce fait, nos amis sont particulièrement tolérants avec nous.</p>
        <a href="https://www.economie.gouv.fr/#" target="_blank" title="Accédez au site de notre sponsor">
            <img src="./assets/img/fisc.jpg" alt="logo du ministère de l'économie Française"/>
        </a>
    </div>
</div>