<!-- ======================================= MAIN ============================================== -->
<main>
    <h1>Qualité</h1>

    <article>
        <h2>Formation de nos agents</h2>
        <p>Nos agent suivent une formation intensive d'une durée de 7 minutes et 44 secondes, afin de vous fournir un service irréprochable.</p>
        <p>La formation vous est fournie ci-dessous, ce qui ne manquera pas de vous rassurer quand à la qualité de la prestation.</p>
        <iframe 
            src="https://www.youtube.com/embed/AObXWpExQdY" title="Formation intensive" 
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" 
            allowfullscreen>
        </iframe>        
    </article>
</main>