<!-- ======================================= MAIN ============================================== -->
<main>
    <h1>Règlement intérieur</h1>

    <article>
        <h2>1) Blabla</h2>
        <p>Lorem ipsum dolor sit amet, consectetur.</p>
        <ul>
            <li>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Totam, dolores.</li>
            <li>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Totam, dolores.</li>
            <li>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Totam, dolores.</li>
            <li>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Totam, dolores.</li>
            <li>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Totam, dolores.</li>
            <li>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Totam, dolores.</li><li>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Totam, dolores.</li>
            <li>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Totam, dolores.</li>
            <li>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Totam, dolores.</li>
        </ul>        
        <p>En cas de non respect vous vous exposez à une sanction.</p>
    </article>

    <article>
        <h2>2) Blabla</h2>
        <p>Lorem ipsum dolor sit amet, consectetur.</p>
        <ul>
            <li>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Totam, dolores.</li>
            <li>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Totam, dolores.</li>
            <li>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Totam, dolores.</li>
        </ul>
    </article>

    <article>
        <h2>3) Blabla</h2>
        <p>Lorem ipsum dolor sit amet, consectetur.</p>
        <ul>
            <li>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Totam, dolores.</li>
            <li>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Totam, dolores.</li>
            <li>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Totam, dolores.</li>
        </ul>
    </article>

    <article>
        <h2>4) Informations sur vos droits</h2>
        <p>
            Vous pouvez consulter vos droits sur 
            <a href="https://www.legifrance.gouv.fr/conv_coll/id/KALICONT000005635405" title="Aller sur légifrance" target="_blank">
                https://www.legifrance.gouv.fr/conv_coll/id/KALICONT000005635405
            </a>
        </p>
    </article>

</main>