<!-- ======================================= MAIN ============================================== -->
<main>
    <h1>Règlement intérieur</h1>

    <!-- First article -->
    <article>
        <h2>1) Tu bosses</h2>
        <p>Tu respecte tout ces points sinon gare à toi.</p>
        <ul>
            <li>T'as interêt à être a l'heure à ton poste</li>
            <li>Tu fera ce qu'on te dira quand on te le dira (même si c'est illégal)</li>
            <li>Tu ne discute pas</li>
            <li>Tu peux te syndiquer, à tes risques et périls</li>
            <li>Si on a oublié tes vacances, t'aura le droit de la fermer</li>
            <li>Tu peux arnaquer les clients si c'est bien fait, mais faudra nous rincer</li>
            <li>Tu peux dealer ou faire du business du moment que c'est discrétos</li>
            <li>Si on te chope a draguer tu vas prendre cher</li>
        </ul>        
        <p>En cas de non respect tu t'exposes à une sanction.</p>
    </article>

    <!-- Second article -->
    <article>
        <h2>2) La tenue</h2>
        <p>Costard obligatoire.</p>
        <ul>
            <li>Propre</li>
            <li>Pas de logo d'un concurrent</li>
            <li>On te fournit pas de tenue, tu t'achetera un costard et tu nous saoule pas avec ça</li>
        </ul>
        <p>Tu seras gentil de pas nous faire passer pour des clodos, on à la classe nous dans notre mafia.</p>
    </article>

    <!-- Third article -->
    <article>
        <h2>3) Le temps de travail</h2>
        <p>T'es au 35 heures, non je déconne PTDR</p>
        <ul>
            <li>Temps de travail maximal quotidien : 12h dans la convention, mais on s'en fou de la loi donc tu pourra faire plus</li>
            <li>Temps de travail maximal par semaine : 48h dans la convention, mais on s'en fou de la convention</li>
            <li>Repos minimal entre deux vacations : 11h selon la convention, mais tu sais ce que je vais dire...</li>
        </ul>
        <p>Tu as le statut de salarié légalement, mais officieusement t'es un esclave, la ramène pas trop !</p>
    </article>

    <!-- Fourth article -->
    <article>
        <h2>4) On t'informe de tes droits</h2>
        <p>
            Tu peux consulter tes droits sur 
            <a href="https://www.legifrance.gouv.fr/conv_coll/id/KALICONT000005635405" title="Aller sur légifrance" target="_blank">
                https://www.legifrance.gouv.fr/conv_coll/id/KALICONT000005635405
            </a>
        </p>
        <p>Mais entre nous tu perds ton temps, on fera chanter les juges si besoin voir pire.</p>
    </article>

</main>