<!-- ======================================= MAIN ============================================== -->
<main>
    <h1>Prestations</h1>
    <!-- Flex container -->
    <div class="data-flex">

        <!-- First article -->
        <article>
            <h2>Magasins</h2>

            <p>
                Sécurisez votre commerce grâce à une équipe d'agents incompétents.
            </p>

            <p>
                Nos équipes ne se préoccuperont pas des voleurs et lorsqu'il y aura
                une altercation (verbale ou physique), ils tourneront la tête, iront
                voir ailleurs ou se retournerons contre vous pour éviter tout
                problème pour eux.
            </p>

            <p>Insécurité totale gartantie.</p>
        </article>

        <!-- Second article -->
        <article>
            <h2>Evènementiel</h2>

            <p>
                Vous avez besoin de sécuriser un évènement type rencontre sportive,
                concert etc ?
            </p>

            <p>
                Nos agents accepterons les pots de vins pour laisser passer
                n'importe qui. En cas d'attentats, ils abandonneront le site pour
                sauver leur peau en priorité.
            </p>

            <p>
                Ils harcèlerons les célébrités pour revendre leurs otographes sur
                internet et divulgueront leurs lieux de repos aux paparazzis contre
                rémunération.
            </p>
        </article>

        <!-- Go Devis button - SVG & BEM__ -->
        <div class="button">
            <a href="demand" title="Faites estimer votre devis et envoyer la demande">
                <svg height="60" width="320">
                    <rect class="button__rect" height="60" width="320"></rect>
                </svg>
                <div class="button__text">Go Devis</div>
            </a>
        </div>

        <!-- Last article (third) -->
        <article>
            <h2>Transports</h2>

            <p>
                En tant qu'établissement recevant du public, vous êtes tenus d'en
                assurer la sécurité. Cependant vous n'êtes pas tenu de le faire bien
                !
            </p>

            <p>
                Nos agents ne seront jamais à leurs postes, il ne respecteront pas
                les usagers ni vos agents. Inutile de nous contacter pour vous
                plaindre de ce type de comportement, ils sont naturels chez nous. En
                cas de dispositifs de colis suspect, nos agents pourraient très bien
                récupérer le sac ou la valise concernée et tenter de garder pour eux
                les effets de valeurs.
            </p>

            <p>
                Nos agents utiliseront leur position sur site pour faciliter nos
                traffics en tous genres.
            </p>
        </article>
    </div>
</main>