<!-- ======================================= MAIN ============================================== -->
<main>
    <h1>Prestations</h1>
    <div class="data-flex">

        <article>
            <h2>Magasins</h2>

            <p>Lorem ipsum dolor sit amet consectetur.</p>

            <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam porro voluptate inventore cumque maiores, 
                magni natus consequatur ipsa enim veniam! Numquam recusandae laboriosam sequi, reprehenderit facere omnis illum hic fugit!
                Debitis totam quis ipsa inventore? Ipsa corporis velit voluptatum iste, fugiat natus exercitationem vel deleniti optio 
                qui dignissimos maiores omnis cupiditate aperiam sapiente iure, culpa hic obcaecati? At, asperiores maxime.
            </p>

            <p>Lorem ipsum dolor sit amet consectetur.</p>
        </article>

        <article>
            <h2>Evènementiel</h2>

            <p>Lorem ipsum dolor sit amet consectetur.</p>

            <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam porro voluptate inventore cumque maiores, 
                magni natus consequatur ipsa enim veniam! Numquam recusandae laboriosam sequi, reprehenderit facere omnis illum hic fugit!
            </p>

            <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam porro voluptate inventore cumque maiores, 
                magni natus consequatur ipsa enim veniam! Numquam recusandae laboriosam sequi, reprehenderit facere omnis illum hic fugit!
            </p>
        </article>

        <div class="button">
            <a href="demand" title="Faites estimer votre devis et envoyer la demande">
                <svg height="60" width="320">
                    <rect class="button__rect" height="60" width="320"></rect>
                </svg>
                <div class="button__text">Go Devis</div>
            </a>
        </div>

        <article>
            <h2>Transports</h2>

            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat, veniam!</p>

            <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex minus aperiam repudiandae nam illo quas 
                praesentium ipsum, recusandae aliquid unde blanditiis esse perferendis sit commodi, perspiciatis animi impedit
                 magni dicta. Dolor unde tempore, iste impedit sequi veniam hic quos voluptatum.
            </p>

            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat, veniam!</p>
        </article>
    </div>
</main>